### PR TITLE
Added Sass, removed extra html templates, js files, and more...

### PR DESCRIPTION
**Pull request by Wkasel**
Lots of big changes, hopefully they work for you guys.

Added Sass support inside the css folder, removed extra template files, left header & footer intact. Swapped CSS to h5bp boilerplate's css, added a config.js file, cleaned up router.js.

### CODE REVIEW

**Comment by timoxley** [comment]
You probably want to remove generated `.sass-cache` files from that sass commit, and add them to the `.gitignore`.

**Comment by timoxley** [comment]
Additionally, SASS on ruby might not be the best way forward since there's already a NodeJS-based server setup in here.

**Comment by timoxley** [comment]
Also, I don't understand why you've changed the whitespace convention for the js files.

**Comment by MRHarrison** [comment]
How about we just use with twitter bootstrap and less, these are more universally accepted.

**Comment by Wkasel** [comment]
Sounds good, but I recall having some errors with bootstrap's js files and require js. Maybe it's worth exploring.

William Kasel
CEO
Gizmo.com

**Pull request closed without merging**
